version: "3"

env_file:
  - .env.example  

services:
  app:
    build: .
    image: hexletcomponents/devops-example-app

  caddy:
    build:
      context: .
      dockerfile: services/caddy/Dockerfile
    image: hexletcomponents/devops-example-caddy
